disabled_rules:
# 비활성화할 규칙들
- trailing_whitespace # 라인 뒤의 공백은 피합니다
- force_cast # 강제 캐스팅은 피해야합니다
- force_unwrapping # 강제 언래핑은 피해야합니다
- line_length # 라인 길이 제한은 적용하지 않습니다

opt_in_rules:
# 선택적으로 활성화할 규칙들
- accessibility_trait_for_button # 버튼 속성의 접근성 트레잇을 체크합니다
- closure_body_length # 클로저의 바디 길이를 체크합니다
- contains_over_filter_count # 필터를 통한 count 보다는 contains를 사용해야합니다
- empty_count # 비어 있는 collection의 count 대신 isEmpty를 사용해야합니다
- fatal_error_message # fatalError 메시지는 빈 문자열이면 안됩니다
- implicit_return # 명시적 return 사용을 피합니다
- multiline_arguments_brackets # 여러줄의 argument에는 괄호를 사용합니다
- multiline_function_chains # 함수 체인을 여러줄로 사용합니다
- multiline_literal_brackets # 여러줄의 literal에는 괄호를 사용합니다
- multiline_parameters # 여러줄의 매개변수 사용을 활성화합니다
- multiline_parameters_brackets # 여러줄의 매개변수에는 괄호를 사용합니다
- vertical_whitespace_between_cases # 케이스 사이에 수직 공백을 사용합니다
- vertical_parameter_alignment_on_call # 함수 호출 시 매개변수의 정렬을 체크합니다
- vertical_whitespace_closing_braces # 닫는 중괄호 전에 공백을 피합니다
- vertical_whitespace_opening_braces # 여는 중괄호 후에 공백을 피합니다

analyzer_rules:
# 분석 규칙들
- unused_import # 사용되지 않는 import를 피합니다
- unused_declaration # 사용되지 않는 선언을 피합니다

closing_brace:
severity: warning # 닫는 괄호 전에 공백을 피해야합니다

colon:
severity: warning # 콜론 주변에 공백을 피해야합니다
flexible_right_spacing: false
apply_to_dictionaries: true

comma:
severity: warning # 콤마 전에 공백을 피해야합니다

control_statement:
severity: warning # 조건문에서 소괄호를 피해야합니다

empty_parameters:
severity: warning # 파라미터가 없는 경우 Void를 사용하지 않습니다

function_body_length:
warning: 300 # 함수의 본문 길이 경고 임계값
error: 500 # 함수의 본문 길이 오류 임계값

leading_whitespace:
severity: warning # 파일의 시작 부분에 공백을 피해야합니다

opening_brace:
severity: warning # 여는 괄호 전에 공백을 사용해야합니다
allow_multiline_func: false # 여러 줄 함수에서 여는 괄호를 허용하지 않습니다

vertical_whitespace:
severity: warning # 코드 사이는 한 줄씩만 띄어야 합니다
max_empty_lines: 1 # 최대 공백 라인 수

vertical_parameter_alignment:
severity: warning # 모든 파라미터는 동일한 들여쓰기를 사용해야합니다

statement_position:
severity: warning # else, catch는 이전 괄호와 동일한 줄에 있어야합니다
statement_mode: default

return_arrow_whitespace:
severity: warning # 반환타입 화살표와 반환 타입 사이에 공백이 한 칸 필요합니다

redundant_set_access_control:
severity: warning # 불필요한 접근 제어 설정을 피해야합니다
